import { NextResponse } from 'next/server';
import { requireApiUser } from '@/lib/api/auth';
import { uploadImage, makeKey, publicUrl, deleteFile } from '@/lib/s3/client';

/**
 * Server-proxied upload route — receives the file bytes and stores them in S3.
 * This is always used (instead of browser-direct presigned PUT) to avoid
 * needing CORS configured on the S3/R2 bucket.
 *
 * Accepts an optional `reservedKey` form field. When provided the file is
 * stored under that key (generated by /api/uploads/preview so the key is
 * consistent). Otherwise a fresh key is generated here.
 *
 * POST /api/uploads/direct (multipart/form-data: file, reservedKey?)
 *   -> { key, mime, previewUrl }
 */

export const runtime = 'nodejs';
export const maxDuration = 30;

const MAX_BYTES = 25 * 1024 * 1024;
const ALLOWED = new Set(['.jpg', '.jpeg', '.png', '.webp', '.svg', '.eps', '.ai']);

const MIME_BY_EXT: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.eps': 'image/x-eps',
  '.ai': 'application/illustrator',
};

function extOf(name: string): string {
  return '.' + (name.split('.').pop() || '').toLowerCase();
}

export async function POST(req: Request) {
  try {
    const user = await requireApiUser(req);

    const form = await req.formData();
    const file = form.get('file');
    if (!(file instanceof File)) {
      return NextResponse.json({ error: 'file_required' }, { status: 400 });
    }

    const ext = extOf(file.name);
    if (!ALLOWED.has(ext)) {
      return NextResponse.json(
        {
          error: 'unsupported_format',
          message: 'Supported formats: JPG, PNG, WEBP, SVG, EPS, AI.',
        },
        { status: 400 },
      );
    }
    if (file.size > MAX_BYTES) {
      return NextResponse.json({ error: 'file_too_large' }, { status: 400 });
    }

    const buffer = Buffer.from(await file.arrayBuffer());
    const mime = MIME_BY_EXT[ext] || file.type || 'image/jpeg';

    // Use the key reserved by /api/uploads/preview if provided,
    // otherwise generate a new one (rasterize route doesn't pre-reserve)
    const rawReservedKey = form.get('reservedKey');
    const reservedKey = typeof rawReservedKey === 'string' && rawReservedKey ? rawReservedKey : null;
    const key = reservedKey ?? makeKey(user.id, file.name);

    // Sanity-check: the reserved key must belong to this user
    // Key format: uploads/<userId>/<timestamp>-<name>
    if (reservedKey) {
      const segments = reservedKey.split('/');
      if (segments[0] !== 'uploads' || segments[1] !== user.id) {
        return NextResponse.json({ error: 'forbidden' }, { status: 403 });
      }
    }

    try {
      await uploadImage(key, buffer, mime);
      const previewUrl = publicUrl(key);
      return NextResponse.json({ key, mime, previewUrl, uploadUrl: null });
    } catch (uploadError: any) {
      console.error('Upload to S3 failed, cleaning up:', uploadError);
      try { await deleteFile(key); } catch {}
      throw uploadError;
    }
  } catch (e: any) {
    console.error('direct upload failed', e);
    return NextResponse.json({ error: e?.message || 'upload_failed' }, { status: 500 });
  }
}

